#!/bin/bash

#
# macdup
#
# VBaddict Dossier Uploader for OSX
#
# Please edit the three variables below to match your account
# You can find/generate your token here : http://www.vbaddict.net/token.php
#

VB_USER=****YOUR_VBADDICT_USER_NAME_HERE****
VB_TOKEN=****YOUR_VBADDICT_TOKEN_HERE****
VB_SERVER=eu

clear
echo "Dossier Uploader for vBAddict"
echo "https://github.com/wolframteetz/worldoftanks/blob/master/README.md"
echo

# upload a file an parse the status
uploadWOTFile(){
    fileType=$1
    url=$2

    uploadFile=`find . -name "$fileType" -mmin -1`
    numberOfFiles=`echo $uploadFile | grep -v "^$" | wc -l`
    if [ $numberOfFiles -ge 1 ]; then
 	echo $numberOfFiles
	message=`curl -s --upload-file "$uploadFile" "$url"`
	parsedStatus=`echo $message | jq ".message" 2>/dev/null`
	if [ $? -eq 0 ] ; then
	    echo $parsedStatus
	else
	    echo "Parsing message returned from the server failed. Received:"
	    echo $message | sed "s/\(upload_file\/.*\/\)\(.*\)\/json/\1TOKEN\/json/"
	fi
    fi
}

while true
do
    # upload the dossier directory
    cd ~/Library/Application\ Support/World\ of\ Tanks/Bottles/worldoftanks/drive_c/users/crossover/Application\ Data/Wargaming.net/WorldOfTanks/dossier_cache
    echo "Number of dossier files"
    uploadWOTFile '*.dat' "http://carius.vbaddict.net:82/upload_file/dossier/$VB_SERVER/$VB_USER/$VB_TOKEN/json"

    cd ~/Library/Application\ Support/World\ of\ Tanks/Bottles/worldoftanks/drive_c/users/crossover/Application\ Data/Wargaming.net/WorldOfTanks/battle_results
    echo "Number of battle results files"
    uploadWOTFile '*.dat' "http://carius.vbaddict.net:82/upload_file/battleresult/$VB_SERVER/$VB_USER/$VB_TOKEN/json"

    cd ~/Documents/WoT/replays
    echo "Number of replay"
    uploadWOTFile "replay*.wotreplay" "http://carius.vbaddict.net:82/upload_file/replay/$VB_SERVER/$VB_USER/$VB_TOKEN/json"

    echo -n "Next check for new dossier files at "
    date -v +1M
    sleep 60
done
